#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Oct 01, 2021 05:15:17 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import start
import rc4_gui

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def openEncRC4Window():
    destroy_window()
    start.processType = 'ENC'
    rc4_gui.vp_start_gui()

def openDecRC4Window():
    destroy_window()
    start.processType = 'DEC'
    rc4_gui.vp_start_gui()

def openImageStegano():
    destroy_window()
    # OPEN STEGANO

def openAudioStegano():
    destroy_window()
    # OPEN STEGANO