#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Sep 05, 2021 05:13:58 PM +07  platform: Windows NT

import sys
from tkinter.ttk import LabeledScale
import easygui

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import start
import rc4_gui
import rc4

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def setTkVariable():
    global keyEntryVar, labelStatusVar
    keyEntryVar = tk.StringVar()
    labelStatusVar = tk.StringVar()
    labelStatusVar.set('Status: ')

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def processNow(procType):
    if(keyEntryVar.get() == ''):
        labelStatusVar.set('Input the KEY first to process')
    else: # Key Value is Exist
        key = keyEntryVar.get()
        if(start.isProcessingBinerFile): # Processing Biner File
            pathFile = easygui.filesavebox(title='Output File (TEXT)')
            f = open(pathFile, "wb")
            if(procType == 'ENC'):
                f.write("")
            elif(procType == 'DEC'):
                f.write("")
            f.close()
        else: # Processing Text File
            if(procType == 'ENC'):
                if(rc4_gui.top.getPlainEntryValue() != ''):
                    rc4_gui.top.setCypherEntryValue(rc4.encr(rc4_gui.top.getPlainEntryValue(), key[:-2], int(key[-1])))
            elif(procType == 'DEC'):
                if(rc4_gui.top.getCypherEntryValue() != ''):
                    rc4_gui.top.setPlainEntryValue(rc4.decr(rc4_gui.top.getCypherEntryValue(), key[:-2], int(key[-1])))
        labelStatusVar.set('Status: Successfully '+procType+'ed')

def loadTextFile(procType):
    fileText = ''
    sys.stdout.flush()
    pathFile = easygui.fileopenbox(title='Select File (TEXT)')
    if (pathFile != None):
        labelStatusVar.set('Status: Successfully load '+pathFile.split('\\')[-1:][0])
        f = open(pathFile, "rt")
        for line in f:
            fileText += line
        if(procType == 'ENC'):
            rc4_gui.top.setPlainEntryValue(fileText)
        elif(procType == 'DEC'):
            rc4_gui.top.setCypherEntryValue(fileText)
        f.close()

def loadBinerFile(procType):
    sys.stdout.flush()
    pathFile = easygui.fileopenbox(title='Select File (TEXT)')
    if (pathFile != None):
        f = open(pathFile, "rb")
        labelStatusVar.set('Status: Successfully load '+pathFile.split('\\')[-1:][0])
        if(procType == 'ENC'):
            rc4_gui.top.setPlainEntryValue(f.read())
        elif(procType == 'DEC'):
            rc4_gui.top.setPlainEntryValue(f.read())
        start.isProcessingBinerFile = True
        f.close()

def saveToFile(PLAINorCYPH):
    pathFile = easygui.filesavebox(title='Output File (TEXT)')
    if (pathFile != None):
        f = open(pathFile,"wt")
        if(PLAINorCYPH == 'PLAIN'):
            f.write(rc4_gui.top.getPlainEntryValue())
        elif(PLAINorCYPH == 'CYPH'):
            f.write(rc4_gui.top.getCypherEntryValue())
        else:
            False
        f.close()
        labelStatusVar.set('Status: Successfully saved to '+pathFile.split('\\')[-1:][0])